db.driverClassName=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://${DB_HOST:localhost}:3306/assetdb?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
db.username=kbulkup
db.password=kbulkup12!@